services:
  frontend:
    build: 
      context : Frontend/.
      dockerfile: dockerfile
    ports:
      - "3000:3000" # Expose frontend on port 3000
    depends_on:
      - backend # Ensure the backend starts first
    environment:
      - CHOKIDAR_USEPOLLING=true # Optional: Prevents file change issues in some environments

  backend:
    build:
      context : Backend/.
      dockerfile: dockerfile
    ports:
      - "10000:10000" # Expose backend on port 10000
    env_file:
      - ./Backend/.env  # env file path
